apiVersion: apps/v1
kind: Deployment
metadata:
  name: gandotechconsoleapp
spec:
  selector:
    matchLabels:
      app: gandotechconsoleapp
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable : 0
  template:
    metadata:
      labels:
        app: gandotechconsoleapp
    spec:
      containers:
      - name: gandotechconsoleapp
        image: gandotech/gandotechconsoleapp:1.0.0.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
